[알파] 2단계: 연관 관계 매핑
woowacourse/jwp-qna pull request #28
Opened 2022-07-12 01:13 UTC by bcc0830

2022-07-14 06:04 UTC, seokhongkim requested changes
알파, JPA 2단계 미션 잘 진행해주셨네요. 👍 
코멘트를 조금 남겼으니 확인 부탁드립니다. 😀

2022-07-14 06:04 UTC, seokhongkim commented on src/main/java/qna/domain/User.java
> +    @OneToMany(mappedBy = "deletedBy")
`User` 가 `DeleteHistory`, `Answer`, `Question` 과 연관관계를 맺어야 할 필요가 있을까요?
언제 연관관계를 맺는 것이 좋고, 연관관계를 맺었을 때의 장단점은 무엇이 있을까요?

2022-07-14 06:04 UTC, seokhongkim commented on src/main/java/qna/domain/MappedEntity.java
> +public class MappedEntity {
`MappedSuperclass` 좋습니다. 👍 
클래스 이름은 고민해보면 좋겠네요. :) `Mapped` 는 `MappedSuperclass` 에서 가져오신 걸까요?

2022-07-14 06:04 UTC, seokhongkim commented on src/main/java/qna/service/QnaService.java
> +        List<Answer> answers = answerRepository.findByQuestionAndDeletedFalse(question);
`Question` 과 `Answer` 과 연관관계를 맺었으니, `Question` 에게 `삭제되지 않은 답변 리스트를 요청`해서 받는 건 어떨까요?
LMS 의 힌트를 참고해봅시다.
```java
Question question = findQuestionById(questionId);
List<Answer> answers = question.getAnswers();
```

2022-07-14 06:04 UTC, seokhongkim commented on src/test/java/qna/domain/AnswerTest.java
> +    @PersistenceContext
테스트 클래스에서도 필드는 상단으로 모아보면 어떨까요?

2022-07-14 06:04 UTC, seokhongkim commented on src/test/java/qna/domain/AnswerTest.java
> +        System.out.println("#####");
의미 없는 코드로 보이는데 삭제하면 좋겠네요!

2022-07-14 06:04 UTC, seokhongkim commented on src/test/java/qna/domain/AnswerTest.java
> +    private void setUp() {
테스트에서 반복적으로 사용되는 엔티티를 미리 저장하는 것이 좋은 것처럼 보이면서도, 각 테스트에서 어떤 조건하에 무슨 행위를 했는지 알기 어려우니 코드 파악이 어려운 면도 있네요.
https://blog.kingbbode.com/52 글을 참고해보셔도 좋겠습니다.

2022-07-14 06:04 UTC, seokhongkim commented on src/main/java/qna/domain/DeleteHistory.java
>      private LocalDateTime createDate = LocalDateTime.now();
이 컬럼도 auditing 을 사용해서 관리해보면 어떨까요?

2022-07-16 13:14 UTC, bcc0830 commented on src/main/java/qna/domain/User.java
> +    @OneToMany(mappedBy = "deletedBy")
연관관계를 맺지 않으면 의존하는 객체를 외래 키를 받지 않는 이상 알 수 없습니다. 그런데, 외래 키를 받아도 결국 Repository에서 조인을 해야 의존하는 객체를 가져올 수 있기 때문에 데이터베이스에 종속되게 됩니다. 따라서, DB상에서 외래 키로 묶인 테이블을 객체에서 참조로도 표현할 수 있게 하는 것이 연관관계의 컨셉이라고 생각합니다. 
 User가 굳이 DeleteHistory와 Answer, Question까지 연관관계를 가져야 할 이유는 다시 생각해보니 없는거 같습니다. 저렇게 연관관계를 맺은 이유는 흔히 "내가 작성한 질문 목록, 내가 작성한 대답 목록"을 가져오려면 User가 Answer나 Question과 연관관계를 맺어 쉽게 가져올 수 있지 않나라는 생각 때문이었습니다.
 그런데 Question만 User를 알고 있는, 즉 다대일 단방향 관계를 맺어도 서비스 레이어에서 전체 Question을 불러와서도 충분히 할 수 있는 작업이라고 생각됩니다. 비슷한 맥락으로 Answer나 DeletedHistory도 같이 처리할 수 있기 때문에 더이상 User가 다른 클래스들과 연관관계를 맺지 않아도 된다고 생각합니다. 또한 기존의 연관관계는 순환참조를 하고 있으므로 설계 상 좋지 않은점도 있다고 생각합니다.
 연관관계를 맺었을 때의 장점은 JPA의 영속성 관리를 통해 어떤 하나의 객체에 대한 수정이 이루어졌을 때 이를 참조하는 객체들의 수정도 가능하게 하는 것이라고 생각합니다. 연관관계의 단점에는 양방향 연관관계 매핑 시 순환참조의 문제가 있고, 정보의 수정이나 삭제 시 양쪽 객체를 모두 관리해야 하며, 무한루프에 빠질 수 있는 위험이 있다고 생각합니다.

2022-07-16 15:08 UTC, bcc0830 commented on src/main/java/qna/domain/MappedEntity.java
> +public class MappedEntity {
네! 생성 시간과 수정 시간을 다루니까 TimeStampEntity라고 수정하였습니다

2022-07-16 15:08 UTC, bcc0830 commented on src/test/java/qna/domain/AnswerTest.java
> +        System.out.println("#####");
수정하였습니다

2022-07-16 15:22 UTC, bcc0830 commented on src/main/java/qna/domain/DeleteHistory.java
>      private LocalDateTime createDate = LocalDateTime.now();
수정하였습니다!

2022-07-16 15:28 UTC, bcc0830 commented on src/main/java/qna/service/QnaService.java
> +        List<Answer> answers = answerRepository.findByQuestionAndDeletedFalse(question);
수정하였습니다!

2022-07-16 15:40 UTC, bcc0830 commented on src/test/java/qna/domain/AnswerTest.java
> +    @PersistenceContext
해당 부분은  Answer를 쿼리를 통해 DB에서 삭제하였을 때 그 영향이 객체에도 전파되는지 테스트하기 위하여 사용하였습니다. 해당 코드는 아래와 같습니다
``` java
@Test
void deleteAnswer() {
    answerRepository.delete(answer1);
    Qusetion question = questionRepository.findById(question1.getId());

    assertThat(question.getAnswer()).isEmpty();
}
```

그런데 해당 테스트는 통과하지 못했고 여러 방법을 했으나 EntityManager의 clear메소드를 통해서는 통과가 되었는데 어떤 이유로 그런지 이해가 되지 않아 테스트 코드를 삭제하였습니다. 혹시 이유를 아신다면 힌트를 주실 수 있을까요?

``` java
@PersistanceContext
EntityManager em;

@Test
void deleteAnswer() {
    answerRepository.delete(answer1);
    Qusetion question = questionRepository.findById(question1.getId());

    em.flush();
    em.clear();

    assertThat(question.getAnswer()).isEmpty();
}
```

2022-07-16 16:01 UTC, bcc0830 commented on src/test/java/qna/domain/AnswerTest.java
> +    private void setUp() {
블로그 포스팅을 참고하여 수정하였습니다!

2022-07-19 07:37 UTC, seokhongkim commented on src/main/java/qna/domain/User.java
> +    @OneToMany(mappedBy = "deletedBy")
연관관계에 대해서 학습도 많이 하신 것 같고, 어떻게 사용하는 것이 좋은지에 대해서도 많이 고민하신 것 같네요.

저는 `User` 가 가지고 있는 `Question` 과의 연관관계도 제거해도 된다고 생각하는데요.
주된 이유는, 현재 `User` 를 통해 `Question` 을 조회할 일이 없기에 연관관계를 추가해서 생기는 복잡성을 지금부터 만들 필요가 없다고 생각하기 때문입니다.

2022-07-19 08:51 UTC, seokhongkim commented on src/test/java/qna/domain/AnswerTest.java
> +    @PersistenceContext
꽤 재밌는 테스트라서 저도 org.hibernate.internal.SessionImpl#doFlush, org.hibernate.internal.SessionImpl#internalClear 를 보고 확인해봤습니다.

먼저, 위에 통과로 작성해주신 테스트도 실패할 것으로 보입니다.
```java
@PersistanceContext
EntityManager em;

@Test // 통과
void deleteAnswer() {
    answerRepository.delete(answer1);
    Qusetion question = questionRepository.findById(question1.getId()); // question 에 맵핑된 answer 가 있는 상태에서 조회한 엔티티

    em.flush();
    em.clear(); // persistence context clear

    assertThat(question.getAnswer()).isEmpty(); // question 을 조회한 시점에는 맵핑된 answer 가 남아있는 상태이므로 실패
}
```

`Answer` 를 삭제했을 때 `Question` 에 맵핑된 `Answer` 가 초기화되지 않는 것은, 현재 `PersistenceContext` 에서 관리하는 `Question` 정보가 변경되지 않았기 때문입니다.
그럼 `delete` 가 호출될 때 어떤 액션이 있는지 볼까요? org.hibernate.event.internal.DefaultDeleteEventListener#onDelete 코드를 참고해보시면 도움이 될 것 같네요.

조금 코드를 보고 추정해본 이유는 있지만, 코드를 따라가며 본 내용은 아니기에 알파가 한번 확인해보시면 도움이 될 것 같습니다. :)
제가 생각한 이유가 궁금하시면 말씀해주세요.

2022-07-19 08:52 UTC, merged