[페퍼] 2단계: 연관 관계 매핑
woowacourse/jwp-qna pull request #32
Opened 2022-07-13 18:04 UTC by SuyeonChoi

2단계 미션 잘부탁드립니다👍
(커밋이 좀 꼬였네요 죄송합니다..)

2022-07-15 07:47 UTC, kang-hyungu requested changes
페퍼 테스트 코드를 다시 점검해보시기 바랍니다.
참고해보면 좋을 자료 남겼으니 수정하셔서 리뷰 재요청주세요.

2022-07-15 07:47 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    protected Answer() {
lombok을 쓰고 있다면 
`@NoArgsConstructor(access = AccessLevel.PROTECTD)`
요런 것도 활용해볼 수 있겠네요

2022-07-15 07:47 UTC, kang-hyungu commented on src/main/java/qna/domain/DeleteHistory.java
> +    @JoinColumn(name = "deleted_by_id", foreignKey = @ForeignKey(name="fk_delete_history_to_user"))
deleted_by_id
테이블에 필드명을 이렇게 가져가는걸까요?

Answer의 writer 필드처럼 적절한 필드명 없을까요?

아니면 DeleteHistory 테이블에 데이터를 생성한 것이니 creator 같은 형식의 필드명은 어떨까요

2022-07-15 07:47 UTC, kang-hyungu commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
모든 repository 테스트에서 DirtiesContext를 제거해보시기 바랍니다.
1. 테스트가 왜 실패했을까요?
2. 영속성 컨텍스트가 무엇일까요? 구글링해보거나 영한님이 쓰신 JPA 책을 참고해봅시다. 유튜브는 아직 보진 못했는데 [최범균님의 JPA 기초 02 코드 구조 & 영속 컨텍스트](https://www.youtube.com/watch?v=7ljqL8ThUts)가 도움이 될거 같네요.

2022-07-15 07:47 UTC, kang-hyungu commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        Question question = questionRepository.save(Q1);
Q1 객체는 작성자가 JAVAJIGI 인가요 SANJIGI 인가요?
객체 연결을 시켜주고 save해줘야 디비에 적절한 테이블에 저장되지 않을까요?

2022-07-15 07:47 UTC, kang-hyungu commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        userRepository.save(JAVAJIGI);
```suggestion
        final val newJavajigi = userRepository.save(JAVAJIGI);
```

왜 이렇게 다시 newJavajigi 변수로 assign 할까요?

2022-07-17 07:21 UTC, SuyeonChoi commented on src/main/java/qna/domain/DeleteHistory.java
> +    @JoinColumn(name = "deleted_by_id", foreignKey = @ForeignKey(name="fk_delete_history_to_user"))
```
create table delete_history
(
    id            bigint generated by default as identity,
    content_id    bigint,
    content_type  varchar(255),
    create_date   timestamp,
    deleted_by_id bigint,
    primary key (id)
)
```

1단계 요구사항에 위와 같은 테이블과 컬럼으로 연관 관계를 매핑하라는 지시가 있어서 일단 이렇게 했습니다! 

바꾸는 게 좋을까요??🥲

2022-07-17 09:55 UTC, SuyeonChoi commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
넵 반영하겠씁니다!

2022-07-17 11:14 UTC, SuyeonChoi commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        userRepository.save(JAVAJIGI);
save 메서드 내에서는 엔티티의 상태에 따라 `merge`(준영속 상태일 수 있기 때문)혹은 `persist`로 분기 처리됩니다. 따라서 실제 리턴되는 객체의 주솟값이 달라지게 되어 메서드 호출 시에는 받아서 할당하는 것이 더 편리합니다.

2022-07-19 01:56 UTC, kang-hyungu commented on src/main/java/qna/domain/DeleteHistory.java
> +    @JoinColumn(name = "deleted_by_id", foreignKey = @ForeignKey(name="fk_delete_history_to_user"))
요구사항에 따라 그대로 진행하시죠!

2022-07-19 01:58 UTC, kang-hyungu approved these changes
페퍼 피드백 반영 잘 해주셨어요
pr은 머지 처리할게요 다음 단계 진행하시죠

2022-07-19 01:58 UTC, kang-hyungu commented on src/main/java/subway/domain/Member.java
> +    private List<Favorite> favorites = new ArrayList<>();
Favorite 클래스가 없어서 컴파일 에러가 생기네요

2022-07-19 01:58 UTC, merged

2022-07-19 02:00 UTC, SuyeonChoi commented on src/main/java/subway/domain/Member.java
> +    private List<Favorite> favorites = new ArrayList<>();
수업때 사용하던 코드도 올라갔었네요!! 다음 단계에서 수정하겠습니다!