[써머] 2단계: 연관관계 매핑
woowacourse/jwp-qna pull request #39
Opened 2022-07-17 10:49 UTC by hyewoncc

안녕하세요, 토미 😄 2단계 PR 제출합니다  
1단계 리뷰 주셨던 내용에 대해 고민한 내용을 지난 리뷰 댓글로 남기려다 PR에 같이 적어봤어요   

1. [MappedSuperclass / Embeddable](https://github.com/woowacourse/jwp-qna/pull/7#discussion_r916776200)  
해당 기능들의 존재를 리뷰를 통해 처음 알게되었는데요 😅
자바docs의 사용 예시와 `상속`/`위임`의 특성을 고려했을 때 `Embeddable`이 더 적합해 보였습니다  
그런데 `Embeddable` 클래스 안에서 `Creation/UpdateTimestamp`를 사용하려니 추측하건데 버전 문제로 되지 않았고,  
`Auditing`은 엔티티인 `MappedSuperclass`에만 적용 가능하더라고요  
결과적으로는 `MappedSuperclass`를 사용했는데 조금 아쉽네요  

2. [상수 픽스쳐 이동](https://github.com/woowacourse/jwp-qna/pull/7#discussion_r916782436)    
제가 작성한 테스트에선 사용하지 않아서, 기존 테스트가 깨질까봐 일단 뒀는데,  
유일하게 사용하는 테스트 클래스 내부로 이동했습니다 
그런데 상수로 픽스쳐를 선언하는 것의 이점을 잘 모르겠어서 3단계에서 다 걷어내려고 해요  

3. [setup 메소드, 테스트 내에서 초기화, 상수로 정의 등 픽스쳐 사용 기준](https://github.com/woowacourse/jwp-qna/pull/7#discussion_r916784576)  
`FK`가 걸린 엔티티와 관련된 테스트를 할 때 마다 고민이 많았던 부분인데요...
현재는 테스트 메서드 간의 확실한 격리를 위해 `테스트 내에서 일회성으로 생성한 뒤 쓰고 버리자`는 방향성을 정해서, 매번 필요한 `User`, `Question`을 생성해주고 있습니다  
하지만 이것도 생성된 픽스쳐가 어떤 픽스쳐인지 보려면 생성해주는 메서드를 찾아가서 읽어야 한다는 불편함이 있어서 여전히 고민되는 부분이네요  
관련해서 더 공부해보도록 하겠습니다!!

늦었지만 2단계도 잘부탁드려요 🙇

2022-07-20 06:59 UTC, seokhongkim commented
써머, 코멘트로 말씀드린 내용에 대해 많이 찾아보고 고민하며 학습하신 것 같네요. 👍 
테스트 관련해서 고민하시는 내용은 https://blog.kingbbode.com/52 블로그를 한번 읽어보셔도 도움이 될 것 같아요!

2022-07-20 07:42 UTC, seokhongkim requested changes
써머, JPA 2단계 미션도 잘 진행해주셨습니다. 👍 
학습을 위해 고민해보셨으면 하는 내용과 추가로 해야 할 작업을 코멘트로 남겼으니 확인 부탁드립니다. 😀

2022-07-20 07:42 UTC, seokhongkim commented on src/main/java/qna/domain/Question.java
>      public void addAnswer(Answer answer) {
질문과 답변이 함께 조회되는 경우가 있고, 질문을 삭제하기 위해 답변의 작성자를 확인하는 것처럼 비즈니스적으로 함께 관리될 필요가 있어 보여요.
질문에서 답변에 대한 연관관계를 추가하고, 삭제할 답변을 조회하는 것도 질문을 통해 가져오도록 변경해보면 어떨까요?

2022-07-20 07:42 UTC, seokhongkim commented on src/test/java/qna/domain/RepositoryTest.java
> +    protected UserRepository users;
현재 구조에서는 레포지토리가 늘어날 때마다 `RepositoryTest` 가 주입받아야 할 객체가 늘어날 것 같아요.
다른 말로 하면, `RepositoryTest` 가 자신을 상속하는 테스트에 의존하는 관계가 된 것으로 보이네요!

2022-07-20 07:42 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
>      public String toString() {
연관관계가 설정된 엔티티의 toString 을 구현할 때 주의해야 할 사항은 어떤 게 있을까요?

2022-07-20 15:16 UTC, hyewoncc commented on src/test/java/qna/domain/RepositoryTest.java
> +    protected UserRepository users;
ATDD에서 공통되는 `get, post...`등의 호출 메서드를 `AcceptanceTest`에 넣고 상속했던 걸 적용해 본거였는데요, 
상속하는 테스트에 의존하게 된다는 관점은 생각하지 못했네요  
왜 생각 못했나 싶을 정도로 당연한 관점이라 생각해 상속 구조를 제거하고, 각 클래스에서 주입받도록 바꿨습니다 😅

2022-07-24 11:58 UTC, hyewoncc commented on src/main/java/qna/domain/Answer.java
>      public String toString() {
양방햔 연관관계가 설정되었을 경우 순환참조로 인해 기존 코드와 같이 `toString()` 구현 시 `stackoverflow`가 발생할 수 있다는 사실을 이번에 처음 알았어요
그래서 해결책을 찾아보니 크게 두 가지가 적합하다 생각했고, 각각 
1. 데이터 반환 시 `toString`을 오버라이드 하지 않고 별도의 `DTO`를 만든다
2. `@JsonManagedReference & @JsonBackReference` 어노테이션을 이용해 직렬화 방향을 설정한다  
였습니다  

1번 방안이 더 좋다고 생각한 것에 더해, 현재 `toString()`을 사용하고 있지 않아 일단 제거했습니다 
3단계에서 필요성을 느낀다면 그 때 다른 방식으로 해결해볼게요

2022-07-24 12:01 UTC, hyewoncc commented
남겨주신 피드백 반영했어요! 🙆

2022-07-25 07:54 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
>      public String toString() {
말씀하신 것처럼 순환참조로 인해 stackoverflow 가 발생할 수 있습니다.

이외에도 toString 에서 사용하는 연관관계를 맺은 엔티티의 fetchType 이 LAZY 인 경우, 트랜잭션 밖에서 toString 이 호출되면 LazyInitializationException 이 발생할 수도 있습니다.
이번에 학습하신 내용을 고려해서 toString 을 작성하면 조금 더 안정적인 프로그램을 만들 수 있겠네요! 👍

2022-07-25 08:01 UTC, seokhongkim approved these changes
써머, 2단계 미션 피드백 잘 반영해주셨습니다. 👍 
엔티티의 toString 구현 시 주의해야 할 내용도 열심히 학습하신 것으로 보이네요!
2단계 PR은 이만 머지하도록 하겠습니다. 코멘트 남긴 내용은 3단계 미션 진행하실 때 참고 부탁드립니다.

3단계 미션에서 뵙겠습니다. 😀

2022-07-25 08:01 UTC, seokhongkim commented on src/main/java/qna/domain/Question.java
> +    private List<Answer> answers = new ArrayList<>();
컬렉션을 클래스로 감싸보는 건 어떨까요?
`삭제되지 않은 모든 답변`의 작성자가 모두 특정한 사람과 일치하는지 물어볼 수 있겠네요!

2022-07-25 08:01 UTC, seokhongkim commented on src/main/java/qna/domain/Question.java
> +        for (Answer answer : answers) {
쿼리에서는 `삭제되지 않은 답변` 만 조회해서 확인했는데, 리팩토링 과정에서 로직이 변경된 것으로 보여요.

2022-07-25 08:01 UTC, merged