[1단계 - 엔티티 매핑] 가비 미션 제출합니다
woowacourse/jwp-qna pull request #53
Opened 2023-07-05 10:48 UTC by iamjooon2

안녕하세요 구구코치님!
리뷰이 가비입니다🙇🏻‍♂️

JPA 1단계 미션 후 리뷰 요청드립니다.

첫번째 커밋인 day1은 제이슨 수업을 들으며 따라친 내용입니다

잘부탁드립니다..!

2023-07-06 00:41 UTC, kang-hyungu requested changes
가비 몇 가지 피드백 남겼어요
수정해보시고 리뷰 재요청주세요~

2023-07-06 00:41 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
한 줄에 하나의 작업만 처리하는게 가독성을 올려줍니다.
```suggestion
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
```

2023-07-06 00:41 UTC, kang-hyungu commented on src/main/java/qna/domain/BaseEntity.java
> +import org.hibernate.annotations.CreationTimestamp;
도메인 객체인데 특정 라이브러리의 어노테이션을 사용했군요!
그리고 스프링이 제공하는 날짜 생성 어노테이션도 있는데 하이버네이트로 사용한 이유는 무엇일까요?

2023-07-06 00:41 UTC, kang-hyungu commented on src/main/java/qna/domain/BaseEntity.java
> +    private LocalDateTime updatedAt;
이 컬럼은 nullable해도 괜찮은가요?

2023-07-06 00:41 UTC, kang-hyungu commented on src/main/java/qna/domain/BaseEntity.java
> +public abstract class BaseEntity {
누가 생성, 수정했는지 시간 외의 정보를 추가해보면 어떨까요?

2023-07-06 00:41 UTC, kang-hyungu commented on src/main/java/qna/domain/DeleteHistory.java
>      private LocalDateTime createDate = LocalDateTime.now();
BaseEntity를 상속 받았으니 필요 없지 않을까요?

2023-07-06 00:41 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>      private String contents;
`@Lob` 이 무엇인지 확인해보고 각 클래스의 적절한 필드에 추가해보시기 바랍니다.

2023-07-06 00:41 UTC, kang-hyungu commented on src/main/java/subway/Station.java
> +@Entity // (1)
주석은 어떤 의미로 남긴걸까요?

2023-07-06 00:41 UTC, kang-hyungu commented on src/main/java/subway/Station.java
> +    public String getName() {
getter()류의 메서드는 최하단으로 배치하세요

2023-07-06 00:41 UTC, kang-hyungu commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    AnswerRepositoryTest(final AnswerRepository answerRepository) {
테스트 코든데 생성자 주입으로 만들 필요가 있을까요?

2023-07-06 00:41 UTC, kang-hyungu commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        final Optional<Answer> result = answerRepository.findByIdAndDeletedFalse(answer.getId());
```suggestion
        final Optional<Answer> actual = answerRepository.findByIdAndDeletedFalse(answer.getId());
```

보통 테스트 코드에서 예상하는 결과값을 담은 변수는 expected, 실제 메서드를 실행한 결과는 actual이라는 변수명을 사용합니다.

2023-07-06 00:42 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>      private boolean deleted = false;
```
deleted     boolean   not null,
```
요구사항의 ddl 조건을 확인해보고 빠진 부분 없는지 체크해보시죠

2023-07-07 00:19 UTC, iamjooon2 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    AnswerRepositoryTest(final AnswerRepository answerRepository) {
수업에서 '@TestConstructor'를 이용해서 생성자 주입을 받는 방법을 알게 되어 적용해보았습니다!

2023-07-07 01:06 UTC, kang-hyungu approved these changes
가비 피드백 반영 잘 하셨어요
pr은 머지 처리할게요. 다음 단계 진행하시죠

2023-07-07 01:06 UTC, kang-hyungu commented on src/main/java/qna/domain/BaseEntity.java
> +    private Long createdBy;
Long 타입으로 하는게 적절할까요?
아이디를 남기는건 어떨까요?

2023-07-07 01:07 UTC, merged