[1단계 - 엔티티 매핑] S-HOOK 팀 미션 제출합니다
woowacourse/jwp-qna pull request #70
Opened 2023-07-10 06:12 UTC by Cyma-s

안녕하세요, 구구! S-HOOK 팀(스플릿, 베로, 바론, 아코) 1단계 미션 제출합니다.

팀원들이 JPA 동작 방식에 익숙하지 않아서 조금 늦었네요 🥹
잘 부탁드립니다 🚀

2023-07-10 07:26 UTC, kang-hyungu requested changes
베로 1단계 미션 잘 진행해주셨네요
몇 가지 수정해보면 좋을 부분에 피드백 남겼어요
확인해보시고 리뷰 재요청주세요.

2023-07-10 07:26 UTC, kang-hyungu commented on src/main/java/qna/Application.java
> +	public static void main(String[] args) {
탭보다 공백 4칸을 사용하세요.
탭을 쓰면 폰트마다 넓이가 달라서 개발자마다 정렬된 상태가 다르게 보입니다.

2023-07-10 07:26 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +@EntityListeners(AuditingEntityListener.class)
모든 도메인 객체에 이 어노테이션이 중복으로 나타나고 있네요
BaseEntity 라는 클래스를 추가해서 한 곳에서 관리하시기 바랍니다.
createdAt, updatedAt 같은 필드도 같이 옮겨보아요

2023-07-10 07:26 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +	@Column(name = "contents")
컬럼 어노테이션 위쪽에 엔터를 하나 더 넣어서 다른 필드와 구분해주세요.

2023-07-10 07:26 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +	@Column(name = "contents")
디비에 null 허용인가요?

2023-07-10 07:26 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
> +	private LocalDateTime createdAt;
필드 순서로 의미있게 정렬해보세요.
다른 개발자가 이 코드를 봤을 때 질문을 생성한 사람이 누구인지 먼저 보이는게 좋을까요?
타이틀, 컨텐츠 같은 질문의 핵심 필드가 먼저 보이는게 코드 파악에 좋을까요?

2023-07-10 07:26 UTC, kang-hyungu commented on src/main/java/qna/domain/User.java
> +@Table(name = "user", uniqueConstraints = @UniqueConstraint(name = "UK_a3imlf41l37utmxiquukk8ajc", columnNames = "user_id"))
UK_a3imlf41l37utmxiquukk8ajc 라는 이름으로 정하는게 좋을까요?
이 값을 보고 무슨 설정인지 파악할 수 있을까요?

2023-07-10 07:26 UTC, kang-hyungu commented on src/main/java/qna/domain/User.java
> +import org.springframework.data.annotation.CreatedDate;
도메인 객체가 특정 프레임워크를 의존하고 있네요.
프레임워크를 바꾸게 된다면 수정해야될 코드가 너무 많을텐데 문제 없을까요?
더 나은 방법 없을까요?

2023-07-10 07:26 UTC, kang-hyungu commented on src/test/java/qna/service/QnaServiceTest.java
> +		Answer answer2 = new Answer(2L, UserTest.SANJIGI, QuestionTest.Q1, "Answers Contents1");
테스트 코드라도 의미 없는 변수명을 사용하지 마세요.
테스트 코드도 유지보수 대상입니다.

2023-07-10 12:14 UTC, Songusika commented on src/main/java/qna/domain/User.java
> +import org.springframework.data.annotation.CreatedDate;
저도 알고 싶어요!

2023-07-11 04:39 UTC, Cyma-s commented on src/main/java/qna/domain/Answer.java
> +@EntityListeners(AuditingEntityListener.class)
`BaseEntity`로 `createdAt`, `updatedAt`을 분리했습니다 ˙ᵕ˙

2023-07-11 04:48 UTC, Cyma-s commented on src/main/java/qna/domain/User.java
> +@Table(name = "user", uniqueConstraints = @UniqueConstraint(name = "UK_a3imlf41l37utmxiquukk8ajc", columnNames = "user_id"))
LMS에 나와있는 DDL을 참고해서 만들었는데, `@Column`에 unique 속성을 true로 해주면 해결된다는 것을 확인하여 변경하였습니다 😄

2023-07-11 04:49 UTC, Cyma-s commented on src/test/java/qna/service/QnaServiceTest.java
> +		Answer answer2 = new Answer(2L, UserTest.SANJIGI, QuestionTest.Q1, "Answers Contents1");
기본 뼈대 코드에 있는 코드고, ServiceTest까지는 미처 확인하지 못했네요 😅 
고쳐두었습니다~

2023-07-11 04:54 UTC, Cyma-s commented on src/main/java/qna/domain/Question.java
> +	private LocalDateTime createdAt;
저희가 중요하다고 생각하는 대로 필드 순서를 다시 정렬해보았습니다 🙂

2023-07-11 04:56 UTC, Cyma-s commented on src/main/java/qna/domain/Answer.java
> +	@Column(name = "contents")
현재 코드는 LMS의 DDL 대로 만들어서 null을 허용한 상태로 만들었는데, 저희가 임의로 필요하다고 생각되는 필드에 `nullable = false`를 추가해도 될까요?

2023-07-11 06:27 UTC, kang-hyungu commented on src/main/java/qna/CannotDeleteException.java
>  public class CannotDeleteException extends Exception {
checked exception과 unchecked exception이 무엇인지 찾아보고 unchecked exception으로 바꿔보시기 바랍니다.

2023-07-11 06:27 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +	@Column(name = "contents")
현재는 미션이니 nullable = false로 바꾸시죠
실무에서는 요구사항이 맞는지 담당자에게 확인하고 작업하시면 됩니다. 현실 세계에서는 정책에 따라 달라질 수 있어요.

2023-07-11 06:28 UTC, kang-hyungu commented on src/main/java/qna/domain/User.java
> +import org.springframework.data.annotation.CreatedDate;
정답은 없으니 실무 가서도 계속 고민해보시죠 ㅋㅋㅋㅋ

2023-07-11 06:29 UTC, kang-hyungu approved these changes
S-HOOK팀 1단계 미션 잘 진행하셨어요.
pr은 머지 할게요 다음 미션 진행하시죠.

2023-07-11 06:29 UTC, merged