[jpa 학습 2단계] 동글팀 연관관계 매핑 제출합니다
woowacourse/jwp-qna pull request #89
Opened 2023-07-12 08:56 UTC by HubCreator

안녕하세요 구구! ㅎㅎㅎ 동글팀 헙크입니다. 이번에 미션을 진행하면서 궁금한 점 몇 가지 질문 남겨보았습니다. 감사합니다 :)

### 1. `@Collumn(nullable = false)` 대신 `@NotNull`을 사용하는 건에 대하여..

컬럼에 null값을 허용하지 않기 위해서 nullable=false를 사용하는 것이 당연하게 생각이 났습니다. 몇 가지 글을 찾아보던 중 데이터베이스 상에서만 null을 허용하지 않을 것이 아니라, @NotNull을 사용하여 필드에 null 값 자체를 오지 않도록 하는 것이 어떨까 라는 생각이 들었습니다. @NotNull을 사용하면 하이버네이트단에서 이를 인지하고 DDL을 만들어준다고 하네요.

물론 이 애너테이션을 사용하면 spring-boot-starter-validation 의존성이 생기긴 해서, 마음에 걸리긴 합니다.ㅎㅎ
구구의 의견은 어떠신지 궁금합니다!

### 2. 엔티티의 생성자에서 `id` 값을 `primitive` 타입으로 받는 건에 대하여..

엔티티의 생성자에서 id 값을 primitive 타입으로 받도록 하면 어떨까 생각했습니다. 외부에서 null이 들어오는 것을 컴파일 타임에 잡을 수 있기 때문에 조금 더 외부에서 null이 들어오는 것에 대해 방어적인 코드가 될 것이라고 생각했기 때문입니다.

여기서 조금 의문이.. 그렇다면 필드의 id 타입도 Long이 아닌 long이면 좋지 않을까? 라는 생각이 들었습니다. 어차피 생성자에서 primitive 타입으로 받았다면 박싱 과정 없이 바로 필드값의 타입에 넣어도 될 것이라 생각했습니다. 괜찮을까요?!?!

한편으로는 Request를 받을 때에 Validation을 위해 래퍼 타입으로 받는 것이 좋다고 하는데, 이때 박싱된 값으로 받고, 이후에 생성자에서 prmitive타입으로 언박싱, id값 매핑에서 또 박싱이 이뤄지는 상황이 생기면 효율이 안좋아질 것 같긴한데... 얼마나 안좋아질까 의문이 들긴 합니다.

이부분도 구구의 의견이 궁금합니다!

2023-07-14 02:30 UTC, kang-hyungu commented
> 안녕하세요 구구! ㅎㅎㅎ 동글팀 헙크입니다. 이번에 미션을 진행하면서 궁금한 점 몇 가지 질문 남겨보았습니다. 감사합니다 :)
> 
> ### 1. `@Collumn(nullable = false)` 대신 `@NotNull`을 사용하는 건에 대하여..
> 컬럼에 null값을 허용하지 않기 위해서 nullable=false를 사용하는 것이 당연하게 생각이 났습니다. 몇 가지 글을 찾아보던 중 데이터베이스 상에서만 null을 허용하지 않을 것이 아니라, @NotNull을 사용하여 필드에 null 값 자체를 오지 않도록 하는 것이 어떨까 라는 생각이 들었습니다. @NotNull을 사용하면 하이버네이트단에서 이를 인지하고 DDL을 만들어준다고 하네요.
> 
> 물론 이 애너테이션을 사용하면 spring-boot-starter-validation 의존성이 생기긴 해서, 마음에 걸리긴 합니다.ㅎㅎ 구구의 의견은 어떠신지 궁금합니다!
> 
> ### 2. 엔티티의 생성자에서 `id` 값을 `primitive` 타입으로 받는 건에 대하여..
> 엔티티의 생성자에서 id 값을 primitive 타입으로 받도록 하면 어떨까 생각했습니다. 외부에서 null이 들어오는 것을 컴파일 타임에 잡을 수 있기 때문에 조금 더 외부에서 null이 들어오는 것에 대해 방어적인 코드가 될 것이라고 생각했기 때문입니다.
> 
> 여기서 조금 의문이.. 그렇다면 필드의 id 타입도 Long이 아닌 long이면 좋지 않을까? 라는 생각이 들었습니다. 어차피 생성자에서 primitive 타입으로 받았다면 박싱 과정 없이 바로 필드값의 타입에 넣어도 될 것이라 생각했습니다. 괜찮을까요?!?!
> 
> 한편으로는 Request를 받을 때에 Validation을 위해 래퍼 타입으로 받는 것이 좋다고 하는데, 이때 박싱된 값으로 받고, 이후에 생성자에서 prmitive타입으로 언박싱, id값 매핑에서 또 박싱이 이뤄지는 상황이 생기면 효율이 안좋아질 것 같긴한데... 얼마나 안좋아질까 의문이 들긴 합니다.
> 
> 이부분도 구구의 의견이 궁금합니다!

1. validation 관련 어노테이션도 표준이 있는걸로 알고 있어요. 잠깐 검색해보니 jsr 303인 것 같은데 정확한 건 좀 더 검색해보시죠 ㅎㅎ
그런데 저라면 NotNull을 쓰지 않고 Column만 사용할거 같네요. 필드에 어노테이션이 많아지면 코드를 보고 관리하기가 힘들더라구요. 너무 많은 정보가 제공되는 것도 좋은 방향은 아닌 것 같아요

2. primitive 로 바꿨을 때 정상적으로 동작하는지 확인해보시죠 ㅎㅎ 저도 primitive 타입을 선호하지만 Long을 써야 제대로 작동할거에요.

2023-07-14 02:43 UTC, kang-hyungu requested changes
동글팀 몇 가지 간단한 리뷰 남겼어요
수정해보시고 리뷰 재요청주세요

2023-07-14 02:43 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
25, 26번째 줄 사이에 엔터로 구분해주면 어떨까여?
너무 붙어있어서 의미 있는 코드 단위로 파악하기가 어렵네요

2023-07-14 02:43 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    @Nullable
nullable을 사용하면 실제 db는 어떻게 설정했는지 코드단에서 확인하기 어렵겠네요. 디비 설정에 대한 정보를 제공하는 목적도 있으니 column을 쓰는건 어떨까요?

2023-07-14 02:43 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
this.id = id;도 이부분으로 옮기시죠
메서드 시작부분은 유효성 검사만 진행하고, 파라미터에 문제가 없으면 의도한 로직을 처리하도록 코드를 의미있게 구분하는걸 추천합니다.
가독성 측면에서도 분리하는게 좋지만 만약 예외가 발생할 상황이라면 this.id = id는 불필요한 처리를 한게 되서 작지만 성능에도 영향을 줄 수 있겠네요.

2023-07-14 04:18 UTC, HubCreator commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
수정하였습니다!

2023-07-14 04:18 UTC, HubCreator commented on src/main/java/qna/domain/Answer.java
> +    @Nullable
넵 ㅎㅎ 수정하였습니다!

2023-07-14 04:19 UTC, HubCreator commented on src/main/java/qna/domain/Answer.java
넵! 제가 놓쳤습니다. 감사합니다 :)

2023-07-17 05:38 UTC, kang-hyungu approved these changes
동글팀 피드백 반영 잘 하셨어요
추가로 남긴 피드백은 다음 단계 진행하면서 적용해보시기 바랍니다.
pr은 머지 처리할게요. 수고하셨어요.

2023-07-17 05:38 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
3단계 미션을 진행할 때 ManyToOne 옵션의 cascade를 고려해보세요.
cascade는 무엇이고 주의할 점은 없을지도 같이 찾아보아요

2023-07-17 05:38 UTC, kang-hyungu commented on src/main/java/qna/domain/BaseEntity.java
> +    @NotNull
여기서 column 어노테이션을 사용하는게 좋겠네요

2023-07-17 05:38 UTC, kang-hyungu commented on build.gradle
1. build.gradle은 들여쓰기를 탭으로 사용하고 있네요.
2. sourceCompatibility = '1.8' 로 되어 있는데 subway 테스트에서 `stations.findByName(expected).orElseThrow().getName();` 같이 더 높은 버전의 기능을 사용하고 있네요.
전체 테스트를 돌려보고 이상 없는지 확인해보세요.

2023-07-17 05:38 UTC, merged