[2단계 - 연관관계 매핑] 페스타고팀 미션 제출합니다
woowacourse/jwp-qna pull request #92
Opened 2023-07-13 02:32 UTC by carsago

구구 이번 리뷰도 잘부탁드립니다 저희 팀은 오리, 글렌, 애쉬, 푸우입니다.

2023-07-13 02:33 UTC, carsago commented on src/main/java/qna/domain/BaseEntity.java
>  public abstract class BaseEntity {
스프링 프레임워크에 대한 의존성을 제거해보았습니다.
사실 지금 미션 코드에서 굳이 이러한 객체가 필요한가..? 라는 의문도 있지만 
저희 팀원들이 잘 모르는 부분이라 학습을 위해서 작성해보았습니다.

2023-07-13 05:48 UTC, kang-hyungu requested changes
페스타고팀 2단계 미션 잘 진행하셨어요
몇 가지 피드백 남겼는데 수정해보시고 리뷰 재요청주세요.

2023-07-13 05:48 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    public void setWriter(User writer) {
answer 객체가 만들어질 때 작성자 없이 만들어질 수가 있을까요?
setter로 작성자를 나중에 설정할 수 있는게 어색해보이네요

2023-07-13 05:48 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    public void setQuestion(Question question) {
setter를 제거할 방법은 없을까요?
question과 answer의 관계를 좀더 고민해보아요

2023-07-13 05:48 UTC, kang-hyungu commented on src/main/java/qna/domain/BaseEntity.java
>  public abstract class BaseEntity {
스프링 의존성을 없애기 위해 PrePersist, PreUpdate를 도입하셨군요
AuditingEntityListener를 쓸 때와 어떤 차이가 있을지도 점검해보면 좋겠네요.
스프링 의존성을 없애는게 정답은 아니고 어떤 장단점이 있을지, 트레이드 오프를 고민해보라는 의미였어요.
지금 방법도 나쁘지 않지만 표준에서 제공하지 않지만 프레임워크가 제공하는 기능을 쓰고 싶을 때는 결국 또 고민하게 될거 같아요.

2023-07-13 05:48 UTC, kang-hyungu commented on src/main/java/qna/domain/DeleteHistory.java
>          this.createDate = createDate;
```suggestion
        this.createDate = LocalDateTime.now();
```

외부에서 시간을 설정하게 만들면 생성 시간을 조작할 수 있겠네요.

2023-07-13 05:48 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
> +    private List<Answer> answers = new ArrayList<>();
일급컬렉션으로 만들면 어떨까요?

2023-07-13 05:48 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
>  public class Question extends BaseEntity {
모든 setter를 제거하시죠!

2023-07-13 05:48 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
>      public Question writeBy(User writer) {
테스트 코드에서만 사용되고 있네요. 필요할까요?

2023-07-13 05:48 UTC, kang-hyungu commented on src/main/java/qna/domain/UserRepository.java
> +import org.springframework.data.jpa.repository.JpaRepository;
UserRepository도 domain 패키지에 속하지만 JpaRepository를 쓰면서 스프링 프레임워크에 의존적으로 되었네요.
요부분은 어떻게 생각하시나요?

2023-07-13 05:48 UTC, kang-hyungu commented on src/main/java/qna/service/QnaService.java
>      }
😱 deleteQuestion(...) 메서드가 너무 길어요
유지보수하기 좋게 10줄 이하로 줄여보시죠

2023-07-13 05:48 UTC, kang-hyungu commented on src/main/java/qna/service/QnaService.java
>      }
앗 2단계 미션 진행중이었군요.
요건 3단계에서 진행하시죠

2023-07-13 08:57 UTC, carsago commented on src/main/java/qna/domain/UserRepository.java
> +import org.springframework.data.jpa.repository.JpaRepository;
JpaRepository 클래스들을 infrastructure 로 내리고 또 한번의 추상화를 진행하려 했으나 너무 큰 추상화 비용이 발생하여 현 상태를 유지하기로 했습니다.
특정한 라이브러리, 프레임워크에 도메인 객체가 의존하는 것은 좋지 않다 생각하지만 Spring 프레임워크의 사용은 변경될 가능성이 매우 적고, 그것을 고려하여 코드의 변경을 하는 것은 조금 과하다고 팀원들과 함께 판단했습니다.

2023-07-14 02:20 UTC, kang-hyungu approved these changes
페스타고팀 피드백 잘 반영하셨어요
2단계 pr은 머지할게요. 다음 단계 진행하시죠.

2023-07-14 02:20 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
> +    public void delete() {
getter를 하단에 위치시키고 객체의 핵심 기능들은 상단에 위치시키는걸 추천합니다.
클래스 파일을 열자마자 핵심 기능이 담긴 메서드를 보는게 어떤 객체인지 파악하기에 더 좋지 않을까요?

2023-07-14 02:20 UTC, merged